title: Ruiyang Qin | 秦睿洋
author: Ruiyang Qin
email: wyattqin@gmail.com
url: "https://qin-roy.github.io"
baseurl: ""
description: >
  Ruiyang Qin is a master's student in Computer Science and Technology at Tongji
  University. His research interests include LLM and agent safety, as well as
  interpretability.
show_excerpts: false

sass:
  sass_dir: _sass

plainwhite:
  name: Ruiyang Qin
  tagline: 秦睿洋
  date_format: "%b %-d, %Y"
  sitemap: true
  search: false
  dark_mode: true
  portfolio_image: "assets/white.png"
  portfolio_image_dark: "assets/black.png"
  html_lang: "en"
  condensed_mobile:
    - page
    - post

  social_links:
    google_scholar: https://scholar.google.com/citations?user=rf0QVMoAAAAJ&hl=zh-CN
    linkedIn: in/ruiyang-qin-a12a05317
    email: wyattqin@gmail.com

plugins:
  - jekyll-seo-tag
